### PR TITLE
fix issue 36

### PR DESCRIPTION
**Pull request by sunny-shu**
now when unpacking the corrupt achive,code will throw badRarArchive exception

### CODE REVIEW

**Comment by gotson** [comment]
Hi, could you add the file provided in #36 along with some tests to validate that it works, and ensure we don't have regression in the future?

**Comment by sunny-shu** [comment]
@gotson 
test case has been added， and I categorized the test cases。

**Comment by gotson** [comment]
Thanks. I think the `JunrarTest` was to test the static class wrapper and the arguments mostly.

Also, I have the new `modernizing` branch ready to go, and it would collide quite a lot with the changes you've done in the tests. If you don't mind I will merge my branch first, then i will adapt the changes you did in this PR to the new branch and merge it.

**Comment by sunny-shu** [comment]
ok，follow  your plan

**Comment by gotson** [comment]
Thanks, i have merged the change. I created a new subtype of exception `corruptHeader` that will be rethrown also, `unsupportedRarArchive` was not meaningful enough IMHO.

**Pull request closed without merging**
