### PR TITLE
support password

### PR DESCRIPTION
**Pull request by sunny-shu**

### CODE REVIEW

**Comment by sunny-shu** [comment]
The code becomes more reasonable after you adjust，
decryption and reading source bytes was mixed  together，Now after your adjustment, I think the decryption should be placed in "ComprDataIO"

**Comment by gotson** [comment]
I checked some papers online and found out the RAR4 encryption is using AES/ECB and not AES/CBC. I'm not sure this changes anything for decryption only though, since we can decrypt fine with both.

Thanks a lot for the refactoring, indeed the code is much clearer like this ! Indeed decryption makes sense to be in ComprDataIO for the moment.

I was playing around with the encrypted file earlier, but i can't get anything out of them :( The documentation of rar says that when header encryption (`hp` parameter) is set, the block headers are encrypted. But with the encrypted archive, i can never get the the header type of the FileHeader block (after the MainHeader block). I tried deciphering the data, but since there is no salt, i had to use an empty salt, but that doesn't work.

If we ever find how to decrypt the headers in Archive class, we may need to move the decryption code from ComprDataIO to another class, but for now it's good here.

I will merge this 👍

**Comment by sunny-shu** [comment]
the RAR4 encryption is using  AES/CBC, You can refer to the official documentation。[https://www.rarlab.com/rarnew.htm](url)。
next i will work on  the file that  the block headers are encrypted.

**Comment by gotson** [comment]
> the RAR4 encryption is using AES/CBC, You can refer to the official documentation。[https://www.rarlab.com/rarnew.htm](url)。

From the website you mentioned, it's about RAR 5, not RAR 4:

> 6. Changes in RAR 5.0 encryption algorithm:
> 
>       a) encryption algorithm is changed from AES-128 to AES-256 in CBC mode.
>          Key derivation function is based on PBKDF2 using HMAC-SHA256;

I found some info [here](http://blog.zorinaq.com/brute-forcing-rar-archives-encrypted-with-the-hp-option/), from someone who cracked RAR 4 encryption:

> When encrypting a RAR archive with "-hp", a random 64-bit salt is generated by RAR, the UCS-2 encoded password is concatenated to the salt, the salt-password pair is hashed with 262144 rounds of a function based on SHA-1, which eventually outputs a 128-bit IV and 128-bit key used to AES-encrypt data blocks in ECB mode.



> next i will work on the file that the block headers are encrypted. how do you think?

If you can work it out that would be great!

I am working on cleaning up the code in `Archive` and `Junrar` to have the right constructors, and to remove the exposition of `VolumeManager` to the consumer.

**Pull request merged**
