### PR TITLE
Allow specific files or folders to be extracted instead of the whole archive

### PR DESCRIPTION
**Pull request by RobbWatershed**
Name says it all... now we can extract specific resources instead of unarchiving everything !
Unit tests are included

### CODE REVIEW

**Comment by RobbWatershed** [comment]
Jesus Christ, style check again... lemme fix that...

**Comment by gotson** [comment]
Didn't had a look in details, but you can already achieve extraction per file via the Archive class.

**Comment by RobbWatershed** [comment]
Then maybe the library doesn't need a new feature but a better explanation of when to use `Junrar` vs. when to use `Archive` ?

**Comment by gotson** [comment]
> Then maybe the library doesn't need a new feature but a better explanation of when to use `Junrar` vs. when to use `Archive` ?

Very true. This library is very old, and I've just recently taken over the maintenance. 

Archive is the real deal, where everything happens and gives you fine control. 

Junrar is merely a utility class for simpler operations. 

Here's an example of how to get a single file extracted : https://github.com/gotson/komga/blob/09984a4284c6ee9a50c7457ea9271fc36c58b770/komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/RarExtractor.kt#L54

You can extract single entries either to a file or to a stream.

Probably what we need is a better Readme!

I don't think adding all features of Archive to Junrar is wise, but that's a personal opinion.

**Comment by RobbWatershed** [comment]
Thanks for the explanations and the gist. I think this will do 👍 

By the way, glad to know another developer who creates apps for comics/manga fans, although we don't share the same target platform nor the same genre of Art 😏

**Pull request closed without merging**
