### PR TITLE
Test first: "fix throw Exception"

### PR DESCRIPTION
**Pull request by beothorn**
@theobisproject I've added unit tests for the exception solution.
The behaviour for the unrar command line tool is to actually decompress the file on the target directory.
For example, if you have an entry ../../foo/bar.txt and decompress it on /tmp you would get /tmp/foo/bar.txt .
I don't think this is a normal scenario, so I think the exception makes more sense.
To open the CVE the fix must be released. I'm still looking on how to make travis do the release.

### CODE REVIEW

**Comment by theobisproject** [comment]
The attached patch fixes the unit tests for my environment (Had to add .txt as filename to upload it here). Feel free to apply it when it also works on your environment.
[Fix_unit_tests.patch.txt](https://github.com/junrar/junrar/files/2800085/Fix_unit_tests.patch.txt)

**Comment by beothorn** [comment]
All green, Thanks!

**Comment by theobisproject** [comment]
@beothorn Any news on this?

**Comment by beothorn** [comment]
I'll not be able to work on this at least till next week.  I will then setup travis to make a release with the fix.

**Pull request merged**
