### PR TITLE
add test for volumed archive and add setting for eclipse in pom.xml

### PR DESCRIPTION
**Pull request by sunny-shu**
this pr is for #9 
there is no test for volumed archive's extraction,so i create it.

### CODE REVIEW

**Comment by gotson** [comment]
Thanks, i'll check.

By the way @sunny-shu i sent you a mail to the email address mentioned in your github profile about project direction, let me know if you did not receive it?

**Comment by gotson** [comment]
the test fails on my computer:

```
arrays first differed at element [1]; 
Expected :testHTML.html: 167
Actual   :testPDF.pdf: 34824
```

**Comment by sunny-shu** [comment]
i will take check

**Comment by gotson** [comment]
I have fixed the Travis build, so you can rebase your changes on the latest commit and update your PR, the checks will run automatically.

**Comment by sunny-shu** [comment]
@gotson  
hi gotson， i'm I'm a little confused，You blocked the script in “.travis.yml”. why The test is still executed。

**Comment by gotson** [comment]
> @gotson
> hi gotson， i'm I'm a little confused，You blocked the script in “.travis.yml”. why The test is still executed。

Travis has defaults for all projects, see here: https://docs.travis-ci.com/user/languages/java/#projects-using-maven

**Comment by sunny-shu** [comment]
@gotson 
hi gotson，the problem has been fixed,you can review the PR when free

**Comment by gotson** [comment]
Thanks a lot for this PR!

**Pull request merged**
