### PR TITLE
Enforce consistent code style through checkstyle maven plugin

### PR DESCRIPTION
**Pull request by theobisproject**
- All the changes do not change the behaviour. Only formatting the code is done.
- The checkstyle rules are based on the sun checkstyle definitions.

Pull Request is opened for discussion. There are still some checks not enabled. Feel free to suggest more checks which should be enabled.

### CODE REVIEW

**Comment by beothorn** [comment]
Thanks for the PR @theobisproject 
I would prefer to have less checks and let the programmer decide on formatting.
For example, forcing brackets would disallow one liners guarding clauses. It makes sense not to always use package visibility even if a method is only being called by classes on the same package because the visibility express intention.
On parameters count, it may be a strong smell that a new class may need to be introduced, but then again it may be not the case. Forcing this would open the code to evolve with classses with undetected unused fields.
Small stuff like spaces before or after an if condition don't interfere with readability but impacts the time between writing code and seeing it run. 

I would keep the checks that don't have any cons like only the unused imports check, upper ell check and spaces instead of tabs for indentation. What do you think?

**Comment by beothorn** [comment]
> Then you are likely to end with the current situation we have where even in the same class different methods follow different formatting styles. 
You are right, but another mechanism to avoid this is pull requests and code reviews. Unfortunatelly I don't know the history of this codebase and how it came to be.

> This Pull Request is for setting a baseline on the formatting to tell a committer how we expect the code to look like.
cool

> If everyone follows the same formatting rules reviews are easier to make because you no longer have to search for the functionality change hidden in all those formatting changes done. Only because the committer didn't like the current formatting style in the class. You could even end up in a "formatting war" where some parts are often changed for the formatting.

Changing code only to change formatting is something that supposedly should come up on a code review. Formatting just for the sake of formatting to someones preference has the negative side effect of showing up whenever someone runs a blame.

> So you mean writing (1) instead of (2)?

Actually I meant
`if (terminationCondition) return someValue;`

I also don't like conditional that are not guarding clauses without parenthesis, but in this case, one liners are more readable because it is clear that each line is one unit and if the termination condition is true nothing that comes afterwards will be executed. 
It is specially cleaner when you have lots of preconditions.

> I don't really know what you wanted to say with the second sentence. Could you make an example?

A new data class is introduced to carry all parameters for a function call even though the function is being called from only one place. 
The code evolves and a field from this parameter class is not used any longer. This will not result in a compiler error.

> The standard value is 7 method parameters. This should be enough for most cases. Otherwise you might have some other design flaws (like violating the Single Responsibility Principle). 
> Also introducing a new class for parameters which belong together is IMHO no design smell

A new class make the fields less clear. You need to open the class to what are the fields you can set. 

> In my experience even those small things matter because you can quickly make a mistake. This blog post even mentions a study which was done about this topic.

I agree that is easier to read code with consistent indentation.
As an aside its been some years since I've seen this, but I vaguely remember those studies being about reasoning about unreachable situations and their shapes, and not about the way they are presented. Going from there to formatting improves is a conclusion that I would not be confident to make.

> I would not matter to much about the time between code written and run. If you set up you IDE correctly you can write the code in every style you want and by simply pressing the formatting shortcut the checkstyle rules are fulfilled automatically.

But the developer still would have to setup the IDE for this.

> As you see this topic is debatable and there is no right and wrong. These rules are made to tell committers "if you make a change we expect you to follow this rules". So those rules will take away some freedom for the formatting style but it increases the readablity and makes reviewing those changes easier because the reviewer can focus on the behaviour changes and does not have to sort out the formatting changes (as statet in the first section).

The true is that I don't use this library anymore. It is just that I fell strongly about automated tools to enforce formatting. As a developer I think it is important to follow the formats of the projects you're working on, even if there is no automated check for this. Maybe that is not how every developer does, but  at least on the places I worked the majority used to do this. 
But I also think the developer must be able to lay the code in a way that hides boilerplate and highlights important code. In a way that aligns related stuff and however they think is the best way to express what a code is doing.

There are pros and cons, I am tending to accept your PR because you are actually working and using this library. There is also the extra point that your name will appear on the blames for every reformatted file.
If you think the pros outweigh the cons I don't see any problem with this PR. I will merge it or if you prefer you can also merge it (you have writing permission to master)

**Comment by theobisproject** [comment]
Now some points are more clear to me which you made in the first comment. I will make some additional work on this over the weekend.  

> if (terminationCondition) return someValue;

A quick look at the documentation shows that this statement can be made valid by an additional property. I then have to check where I have already changed those statements 😉

I would propose to remove the `ParameterNumber` check as you suggested but keeping all the whitespace checks for consistency. Any objections?

> I will merge it or if you prefer you can also merge it (you have writing permission to master)

It is alway good to have onther person looking at the changes. This is the reason I would avoid merging it by myself :smile:

**Comment by beothorn** [comment]
Merged on https://github.com/junrar/junrar/pull/30
(sorry, somehow created a new branch fixing the conflicts, but all your changes are there)

**Comment by theobisproject** [comment]
No problem. Thanks for merging!

**Pull request merged**
